### ISSUE TITLE
Review l0-path-constraints grouping

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang#16]
Few questions:

1. It seems identical to the wson-path-constraints grouping. Should it be moved to layer0-types-ext and imported instead?
2. Should this grouping also needed to provide path constraints for tunnel setup?

**Comment by danielkinguk** [comment]
"1. It seems identical to the wson-path-constraints grouping. Should it be moved to layer0-types-ext and imported instead?" moved to Layer-0.

**Comment by italobusi** [comment]
> 2\. Should this grouping also needed to provide path constraints for tunnel setup?

Still need to be addressed

**Comment by sergiobelotti** [comment]
The grouping is used in the request of tunnel input rpc, to provide the way to choose wavelength assignment e.g. randomly or taking into account residual capacity.

**Comment by italobusi** [comment]
IMHO, if this attribute is an input for the path computation, it should be also provided in the TE tunnel model and not only in the path computation RPC

Two doubts:
1. is this attribute defined/applicable per-tunnel or per-path? In other words, it is possible to apply different wavelength assignment mechanisms to the primary and secondary paths of the same tunnel?
2. where are these mechanisms defined? The layer0-types-ext model references RFC 6163 but I am not able to find any definition of first-fit, random selection or residual capacity in RFC 6163 ...

**Comment by danielkinguk** [comment]
Italo and Sergio to discuss open issue next week, prior to our next call.

**Comment by sergiobelotti** [comment]
> @sergiobelotti : I agree that this attribute is useful for optical path computation
> 
> IMHO, if this attribute is an input for the path computation, it should be also provided in the TE tunnel model and not only in the path computation RPC, so the grouping should be used in other parts of the model and not only in the path computation RPC augmentation
> 
> Two doubts/questions:
> 
> 1. is this attribute defined/applicable per-tunnel or per-path? In other words, it is possible to apply different wavelength assignment mechanisms to the primary and secondary paths of the same tunnel?
> 2. where are these mechanisms defined? The layer0-types-ext model references RFC 6163 but I am not able to find any definition of first-fit, random selection or residual capacity in RFC 6163 ...

The wavelength-assignment method are just described by the identities defined in layer0-types-ext:

identity wavelength-assignment {
    description
      "Wavelength selection base";
    reference
      "RFC6163:Framework for GMPLS and Path Computation Element 
      (PCE) Control of Wavelength Switched Optical Networks (WSONs)";
  }

  identity unspecified-wavelength-assignment {
    base wavelength-assignment;
    description
      "No method specified";
  }

  identity first-fit-wavelength-assignment {
    base wavelength-assignment;
    description
      "All the available wavelengths are numbered,
       and this WA (Wavelength Assignment) method chooses
       the available wavelength with the lowest index";
  }

  identity random-wavelength-assignment {
    base wavelength-assignment;
    description
      "This WA method chooses an available
       wavelength randomly";
  }

  identity least-loaded-wavelength-assignment {
    base wavelength-assignment;
    description
      "This WA method selects the wavelength that
       has the largest residual capacity on the most loaded
       link along the route (in multi-fiber networks)";
  }

**Comment by italobusi** [comment]
**2021-11-29 Aihua/Italo/Sergio**

The wavelength-assignment attribute should be defined for both path computation RPC and tunnel models.

The attribute is defined per-tunnel and therefore should be moved to the l0-tunnel-attributes grouping.

The definitions of the possible wavelength-assignment values is well known in literature but not defined in any standard document. It may be clarified in the layer0-types-ext text.

@agva123 : please provide some reference in the literature

Since the wavelength-assignment attribute is optional, there is no need for the unspecified-wavelength-assignment identity. When the wavelength-assignment is not present no wavelength-assignment method is specified.

**Comment by danielkinguk** [comment]
Waiting on Sergio and Italo to update the model, then we can close the issue.
