### ISSUE TITLE
Investigate potential YANG Compilation Errors with Latest Version of Code. 

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang#38]
Check with Daniel P.

**Comment by italobusi** [comment]
We have found similar issues with the MW topology YANG

See: https://github.com/YangCatalog/bottle-yang-extractor-validator/issues/74

**Comment by danielkinguk** [comment]
Still unsure why it does not compile/validate. Daniel P is on the case.

**Comment by dperdices** [comment]
First issue solved after a couple of hours of debugging the YANG validator. Solution:

**Delete L9 of the YANG model (https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang/blob/master/ietf-flexi-grid-tunnel.yang#L9).** 

It doesn't like that date (and I don't know exactly why 😕).

Now, we do have the validation report:

```
Pyang Validation
No warnings or errors
Pyang Output
No warnings or errors
Confdc Output
ietf-te@2021-10-22.yang:298) is converted to 'string' when part of a union
ietf-te@2021-10-22.yang:302) is converted to 'string' when part of a union
Yanglint Validation
libyang err : Invalid default - value does not fit the type (Invalid identityref "flexi-ch-spc-6p25ghz" value - identity not found in module "ietf-flexi-grid-tunnel".). (Schema location /ietf-te:te/tunnels/tunnel/secondary-reverse-paths/secondary-reverse-path/path-out-segment/label-restrictions/label-restriction/label-step/technology/ietf-flexi-grid-tunnel:flexi-grid/flexi-grid-channel-spacing.)
YANGLINT[E]: Processing schema module from /var/yang/tmp/yangvalidator/yangvalidator-v2-workdir-qnXKFzYD/ietf-flexi-grid-tunnel@2021-10-25.yang failed.
Yangdump-pro Validation
No warnings or errors
```

The only clear error is:
```
Invalid default - value does not fit the type (Invalid identityref "flexi-ch-spc-6p25ghz" value - identity not found in module "ietf-flexi-grid-tunnel".
```
which has to do with this augment (https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang/blob/master/ietf-flexi-grid-tunnel.yang#L870) and happens to be the last one using l0-types:flexi-grid-label-step:
```
 augment "/te:te/te:tunnels/te:tunnel/"
        + "te:secondary-reverse-paths/te:secondary-reverse-path/"
        + "te:path-out-segment/te:label-restrictions/"
        + "te:label-restriction/te:label-step/te:technology" {
    description
      "Augment TE label range step for the egress segment
      of the secondary reverse path.";
    case flexi-grid {
      uses l0-types:flexi-grid-label-step;
    }
  }
```
To be discussed on Thursday meeting.

**Comment by danielkinguk** [comment]
Thanks for the debugging Daniel. 

Looks to be an issue with the online tool "flexi-ch-spc-6p25ghz" is not valid, it has to be an issue with YANG tool. 

https://github.com/YangCatalog/yang-validator-extractor

Daniel P will log an issue with the YANG Tools repository.

**Comment by dperdices** [comment]
Done in https://github.com/YangCatalog/yang-validator-extractor/issues/84 and https://github.com/YangCatalog/yang-validator-extractor/issues/85.
